service: bigjson
provider:
  name: aws
  runtime: python3.7

plugins:
  - serverless-offline-python

functions:
  big_json:
    handler: handler.big_json
    events:
      - http:
          path: /bigjson/
          method: get
custom:
  serverless-offline:
    host: 0.0.0.0
